global:
  checkNewVersion: false
  sendAnonymousUsage: false

log:
  level: "INFO"

entryPoints:
  http:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: https
  https:
    address: ":443"

providers:
  file:
    filename: "/etc/traefik/traefik.yml"
    watch: true
  docker:
    watch: true
    exposedByDefault: false

certificatesResolvers:
  ovh:
    acme:
      caServer: https://acme-staging-v02.api.letsencrypt.org/directory
      storage: "acme.json"
      email: "_____REPLACE_ME_____"
      dnsChallenge:
        provider: "ovh"
        delayBeforeCheck: 10
